### ISSUE TITLE
Ranking in the server results in unordered beacons in Android App.

### ISSUE THREAD

**Issue by g-ortuno** [google/physical-web#402] opened 2015-05-26 22:00 UTC
Current flow:
1. Scan for two seconds (Also send requests to PWS)
2. Stop scanning
3. Order beacons. Beacons with no metadata will be pushed to the end.
4. Show beacons. Beacons with no metadata will be shown as "loading...". No matter what the rank returned by the server is, the beacons will stay at end of the list.

**STEPS TO REPRODUCE**
1. Open app

**EXPECTED BEHAVIOR**
See ordered list based on proximity.

**CURRENT BEHAVIOR**
Beacons for which ranking is not available by the time the beacons are shown are pushed to the end of the list, even if they are a couple inches away from the phone.

**Comment by dinhviethoa** [comment] 2015-05-26 22:02
Could you describe the steps to reproduce, the expected behavior and the current behavior?

**Comment by g-ortuno** [comment] 2015-05-26 22:09
Done.

**Comment by scottjenson** [comment] 2015-05-26 22:25
Thanks for this Gio, we've discussed this issue a few times recently in our team meetings. Right now we are assuming we can't show a result until it comes back from the PWS. The reason is that the PWS has gained a few new powers recently:
1) The PWS can rank something low or high (so showing it close could be a mistake) This allows us to add Google Safe search support in the future so we can push down beacons that might be spammy
2) The PWS can remove items entirely (for very bad beacons)
3) We have redirector support so the URL service itself can be involved, it can remove a device from the list based on any criteria they wish.

So this means that we can't show an item on the list until we hear back from the PWS. This indeed does introduce a delay but we felt the ranking decisions were likely to get more and more complex and it would be better to offload that from the client.

However, note that this is the direction we are taking for our client. If other company wanted to make an alternative client that used ONLY distance, that would be possible.

**Comment by g-ortuno** [comment] 2015-05-26 22:28
Yes. I know that :) I just wanted to document/point out that we will have some ranking problems because now we go through the server and our current logic doesn't handle that as gracefully as it could.

**Comment by dinhviethoa** [comment] 2015-05-26 22:29
I think that's in our plan to remove the beacons that don't have metadata from the list.
It will probably make the ranking looks better.

**Comment by scottjenson** [comment] 2015-05-26 22:31
Sorry, then I misunderstood your issue. I thought you wanted to show everything and our goal is to remove things that don't resolve. Sounds like we're in agreement then ;-)

**Comment by g-ortuno** [comment] 2015-05-26 22:34
Yeah. If you suddenly see a beacon that's right next to you at the end of the list it might be because the metadata didn't arrive in time.

**Comment by dinhviethoa** [comment] 2015-05-26 23:02
I'll close this one and open a more accurate issue.

**Closed by dinhviethoa** 2015-05-26 23:02 UTC
