### ISSUE TITLE
Physical does not show up if chrome cache is deleted 

### ISSUE THREAD

**Issue by kanodia** [google/physical-web#645] opened 2016-05-05 15:12 UTC
Hello

When I delete chrome data or chrome cache by going to android app settings, physical web goes away.

Also, I checked in privacy settings, I cannot find physical web option.

Is it a bug. What can be done to get it back?

**Comment by scottjenson** [comment] 2016-05-05 15:33
Actually, it's not a bug :) as we are behind a feature flag, when you delete the chrome cache you need to resync with the chrome server to reset the flag. This can take a little while (up to an hour)

This is clearly NOT a good experience but this is how all new features are released in Chrome (default off, turned on by server) This gives us better control in case a feature causes problems. As the Physical Web is doing well and not causing problems, we are going to flip the flag to 'default on' which means that you won't see this problem any more. Not sure which release it will be in in but it'll be 2-3 months from now (we release every 6 weeks)

**Comment by kanodia** [comment] 2016-05-05 19:02
Thank You Scott for the clarification. I will test it on my google chrome to see the behavior

Thanks

**Closed** 2016-05-11 05:45 UTC
