### ISSUE TITLE
ver 0.1.801 responsive

### ISSUE THREAD

**Issue by tolson2000** [google/physical-web#253] opened 2014-12-26 19:40 UTC
My nexus 7 updated from 0.1.737 to 0.1.801.
FYI,
Responsiveness has deteriated greatly to almost nil.

**Comment by g-ortuno** [comment] 2015-01-07 20:42
@tolson2000 I am currently looking into this issue. Could you answer a couple of questions so I can find out the cause of your issue?
1. What Android version are you using?
2. What type of beacon are you using? What is the beacon's broadcasting period and Tx Power Level?
3. Could you walk us through the steps to reproduce the problem?

**Comment by tolson2000** [comment] 2015-01-07 22:53
1. version 4.4.4.
2. RFduino. Very similiar to example in Uribeacon beacons folder except using urischeme 0x02 for http:// instead of http://www. and my domains. Actual programmed power to the nRF51288 is +4dBm. The adveritzed uribeacon power at 0 meters is 0xEE (-18dBm). Adv Interval is 1000ms.
3. Let the update happen. Enter the app. Nada!

I can watch my logs on my servers and see activity being accessed by your googleusercontent.com servers and the AppEngine-Google s~url-caster.

Even see the favicon.ico being grabbed by my real IP. 
But nothing happens on the physical web app screen.

**Comment by schilit** [comment] 2015-01-08 07:23
What is the URL you are advertising?

**Comment by tolson2000** [comment] 2015-01-08 08:22
I have several that work with the 1.737.
http://io.ivt.com/1
http://io.ivt.com/x?5

**Comment by g-ortuno** [comment] 2015-01-12 19:30
Fixed by #259

**Closed by g-ortuno** 2015-01-12 19:30 UTC

**Comment by g-ortuno** [comment] 2015-01-22 17:05
FYI a new version of the app which fixed the issue was pushed to the Play Store. Please update to that version and let us know if there are any problems.
