### ISSUE TITLE
Physical Web down !?

### ISSUE THREAD

**Issue by LOC-Place** [google/physical-web#907] opened 2017-05-08 10:21 UTC
Since Sunday CET we don't get physical web redirects
Started with tiny.cc codes and now (today Monday 8th of May) seems to be down totally?
Problems on different (nearly all) iOS and Android versions

**Comment by ferencbrachmann** [comment] 2017-05-08 12:28
Same here!

**Comment by luciofr** [comment] 2017-05-08 12:39
Personally, since last week the native Android Nearby has been presenting problems intermintentes, what surprised me was that the Physical Web application and the Chrome Notifications in iOS since 04 / May, began to present the same problem, we need an answer About what is happening, does the Eddysotne Project continue or will it be discontinued? A few thousand dollars have been invested and we need to know what is happening, my support center is full of shit.

**Comment by raphbibus** [comment] 2017-05-08 13:01
Same here, no Nearby Notifications. Only app working is the Physical Web app on iOS right now.

**Comment by mahnuh** [comment] 2017-05-08 13:07
Can confirm this, only physical web app and third-party apps working on iOS.

**Comment by LOC-Place** [comment] 2017-05-08 13:08
Physical Web APP on iOS is still working
NOT on Android!
@scottjenson - meeting in vienna - sent you a related private message too.

**Comment by mahnuh** [comment] 2017-05-08 13:15
The problem might be the physical web proxy?

**Comment by kevinahuber** [comment] 2017-05-08 14:07
Confirmed here. Test site is failing too: 
https://github.com/google/physical-web/issues/907

**Comment by mmocny** [comment] 2017-05-08 14:23
Sorry folks, server outage last night for several hours.  Back up now, let me know if you see anything else!

(Buy you folks are fast at noticing!)

**Comment by mahnuh** [comment] 2017-05-08 14:30
Chrome on iOS is working again.

**Comment by kevinahuber** [comment] 2017-05-08 14:33
Awesome! As with speed, @luciofr (and the rest of the folks here) are dependent on these services for demos and active deployments. 

@mmocny With experimentation and tweaking happening, it's difficult to determine what is an experiment vs. an unintentional outage. Could we develop a clearer channel to disseminate whether not seeing physical web content is the result of a change in URL resolution method, rollout/rollback of feature, etc.

**Comment by raphbibus** [comment] 2017-05-08 14:39
Tested on Android 7 and iOS, works fine again. Suggesting to close this issue.

**Comment by mmocny** [comment] 2017-05-08 14:41
@kevinahuber I think the test you did (just using the [validator](https://beaufortfrancois.github.io/sandbox/physical-web/url-validator/)) is a great way to isolate for server issues.

Apologies again!

**Closed by mmocny** 2017-05-08 14:41 UTC

**Comment by LOC-Place** [comment] 2017-05-08 14:43
Worked on Android five minutes ago for a view minutes
NOW and again NO SERVICE!
iOS Chrome Plug-In didn't work even during the time when Android worked.
Suggestion NOT to close this issue yet :-(
Still testing and will let you know when the issues on my side here in Europe/Austria are solved.
Give the serves/cashes etc. a chance to recover in the next hours.
Will keep you informed

**Comment by LOC-Place** [comment] 2017-05-08 14:45
@mmocny can you reopen the issue or do I have to open a new one?

**Comment by LOC-Place** [comment] 2017-05-08 14:48
working again on Andorid

**Comment by LOC-Place** [comment] 2017-05-08 14:56
NOT stable 
again NOT working on Android

**Comment by mahnuh** [comment] 2017-05-08 14:58
Working like charm on our android devices.

**Comment by luciofr** [comment] 2017-05-08 16:00
Here in Brazil nothing works, Nearby Android native (since last week), Physical Web Application and iOS via Chrome Notifications (04 / May).

**Comment by jeffprestes** [comment] 2017-05-08 16:05
For me, in Brazil, it's working normally.

**Comment by luciofr** [comment] 2017-05-08 16:16
@jeffprestes are you receiving your notifications via Nearby native Android, Physical Web Application and iOS via Chrome Notifications? Could you send us the print of your canvases? Do you use your own URLs or are you using a default of type https://www.google.com?

**Comment by LOC-Place** [comment] 2017-05-08 16:22
Please compare my new open issue #908
Physical Web Service totally unstable - fails to validate URLs #908

If you don't get any nearby notifications try to validate your url here:
Nearby does filter some page content if it gets swiped away too many times. You may have ran into this. Please also try the URL validator: 
https://beaufortfrancois.github.io/sandbox/physical-web/url-validator/

**Comment by luciofr** [comment] 2017-05-08 16:48
I have at least 30 nearby Beacons, all with valid URLs.
![physical vali](https://cloud.githubusercontent.com/assets/27795008/25814707/cb0b6832-33f4-11e7-9908-d474b7fd7677.JPG)
