### ISSUE TITLE
Support UPnP Basic Device Discovery

### ISSUE THREAD

**Issue by louaybassbouss** [google/physical-web#255] opened 2015-01-06 14:51 UTC
Physical-web supports now BLE and mDNS for advertising URL/URIs. What about UPnP or SSDP? it is similar to mDNS. The [UPnP Basic Device Profile](http://upnp.org/specs/basic/basic1/) could be used to advertise an URL in a Network similar to mDNS. `<presentationURL>URL for presentation</presentationURL>` in the device description is a potential candidate to put the URL. 
Another lightweight solution could be by using SSDP only without the complexity of parsing UPnP Device Description to get the Presentation URL  by advertising the URL in the SSDP message as a new property.

**Comment by scottjenson** [comment] 2015-01-06 15:16
Thanks for raising the issue. There are a number of services that we could support it's really a matter of time and impact. To be honest, I'd like to know more about UPnP/SSDP. I understand what they do technically but I'd like to know if they're growing or shirking in usage. For example, UPnP has been around for a quite a while but it doesn't appear to be growing much. In addition a few folks I've discussed this with had some, er, less the complimentary comments about it's ability to actually work properly. However, this is clearly meant as a request for info. Are either of these actually doing very well? Am I being a bit too skeptical?

**Comment by louaybassbouss** [comment] 2015-01-06 15:37
Thx for quick reply. I am a researcher from [Fraunhofer FOKUS](http://www.fokus.fraunhofer.de/) I work in the Multi-screen domain and have experience in network discovery protocols. I don't want to make advertisement for UPnP or DLNA but I think they are growing. according to [DLNA](http://www.dlna.org/dlna-for-industry/certification/product-search) , there are currently more than 3 billion certified devices/products on the market. almost every Smart TV is DLNA certified. Furthermore the DIAL protocol is based on SSDP and is also supported on billion of devices. Also [UPnP 2.0](http://upnp.org/sdcps-and-certification/standards/device-architecture-documents/)  considers will consider IoT and lot of new features. From my point of view, if physical-web considers mDNS as a discovery protocol to advertise URLs in a local network, it makes also sense to consider UPnP or SSDP in the same way. If group members agree on this feature, we can contribute with a prototype implementation for Android and/or iOS.

**Comment by scottjenson** [comment] 2015-01-06 15:52
We'd love to have your input/help on this issue. Thank you! There are two parts to this problem: broadcasting and receiving. If you would contribute, would you help with both pieces or would you focus on the broadcasting?

One thing we learned from our mDNS work that is relevant here: it's likely that a device will broadcast a local URL, not a publicly available one (e.g. myTV.local vs cnn.com).  As the Physical Web uses a central proxy for all URLS (this helps with privacy but is also used to cache meta data such as title, Description and favicon. There are lots of advantages to this but of course the big drawback is that a global proxy server can't see your local URLs. 

So just this week, we are discussing/adding this meta data to the mDNS broadcaster. It's fairly easy to do, I'm just letting you know that in addition to broadcasting a URL, it will need to broadcast a Title, a description, and an optional favicon (which can be a global URL if necessary)

This is likely just a bit more markup/structure to what is being broadcast so shouldn't be hard. Let me know if I explained this clearly, I'm happy to have a video/phone call if you'd like to discuss further.

**Comment by louaybassbouss** [comment] 2015-01-06 20:39
We will contribute on both parts broadcasting and receiving. For broadcasting we will support nodejs (win, linux and mac) and receiving Android , iOS and nodejs. 

I already tested the last iOS physical web app with my own local web server with mDNS advertising and recognized that only the urls are displayed without title, description, etc. It makes sense to adverstise these information also via mDNS and in the same way for UPnP/SSDP. Another solution is to fetch the web page directly in the App and not on the server but this requires more computing resources on the mobile device. 

For UPnP/SSDP it is easy to advertise the additional information I think in UPnP basic device profile there are already field for name, icon and maybe description. We can also use SSDP without device description xml and pass all parameters in the SSDP message. This is faster than fetching the xml device description.

**Comment by dinhviethoa** [comment] 2015-01-06 21:47
Could you send a link to the "basic device profile"?
I think you could start contributing with the URL without metadata for now.
We'll investigate metadata in a second step.
Thanks!

**Comment by louaybassbouss** [comment] 2015-01-06 22:08
[UPnP Basic Device](http://upnp.org/specs/basic/UPnP-basic-Basic-v1-Device.pdf). Yes I think we will start first with URL without metadata.

**Comment by louaybassbouss** [comment] 2015-01-09 13:51
I collected some ideas for [UPnP/SSDP support in Physical Web](https://github.com/louaybassbouss/louaybassbouss.github.io/blob/master/physical-web/upnp_ssdp_support.md). Feel free to review and comment.

**Comment by scottjenson** [comment] 2015-01-31 21:00
Just confirming that you are working on this. Are you waiting for anything from us?

**Comment by louaybassbouss** [comment] 2015-01-31 22:35
Hi Scott yes i am working on it you can expect first working version for Android (receiver) and node.js (sender for test purposes) by end of next week.

Regards,
Louay

On 31 Jan 2015, at 22:01, scottjenson <notifications@github.com<mailto:notifications@github.com>> wrote:


Just confirming that you are working on this. Are you waiting for anything from us?

**Comment by scottjenson** [comment] 2015-03-04 21:33
We're waiting on you at this point. I appreciate that you need to get back from legal but I just want to point out that the longer you wait, the harder it is going to be to merge (as the files will change under you). Is there any feedback from your legal department? 

Scott

**Comment by louaybassbouss** [comment] 2015-03-05 13:42
finally I get approval from our legal department and the CLA is signed. I pushed a new version and the issues mentioned in the comments of PR #291  are solved. Once the PR is merged we can talk about next steps.Let me know if you have additional questions or comments.

Louay

**Comment by matthewsibigtroth** [comment] 2015-03-05 19:05
Hello!
Under what name(s) was the CLA signed just so we can verify on our end.
Thanks,
matt

**Comment by louaybassbouss** [comment] 2015-03-05 19:28
Hello, the CLA is signed by Stephan Steglich (stephan.steglich@fokus.fraunhofer.de). Authorized Contributors Group:  fraunhoferfokus-google-contributors@googlegroups.com<mailto:fraunhoferfokus-google-contributors@googlegroups.com> . I am in the group as louay.bassbouss@fokus.fraunhofer.de<mailto:louay.bassbouss@fokus.fraunhofer.de> (it is the primary mail address for my github account louaybassbouss ).

Louay

**Comment by scottjenson** [comment] 2015-03-05 19:35
Well the issue is that the CLA must match up with the person that makes the pull request. This still might be possible, I'm just a bit confused as to what you've actually done.

You'll either have to add your email to your Github account or get Stephen to push the merge (which I understand is likely very hard to do)

Please clarify a bit what is going on here and if you can just sign from your github account. That would be the simplest thing to do. 

Scott

**Comment by scottjenson** [comment] 2015-03-18 04:08
All in and completed. closing now

**Closed by scottjenson** 2015-03-18 04:08 UTC
