### ISSUE TITLE
Why is physical web eddystone-url so unreliable on Android vs iOS

### ISSUE THREAD

**Issue by funkybudda** [google/physical-web#720] opened 2016-07-07 15:38 UTC
hi,

a few colleague and I started to play around with physical web using few Estimote beacons, and the result on Android has been very unreliable.

We browsed the open issues on here and based on @kanodia's method here seem to be the most reliable to get the physical web notification to show up:
https://github.com/google/physical-web/issues/670

But even with that method, we are still have consistency issue in getting notifications. On the iOS devices we tested, the notification just WORKS. The test was done with one beacon emitting one test eddystone-url.

Now we turned on a 2nd beacon, and on Android, we are still seeing inconsistency with physical web notificaion popping up, but on top of that, it is always ONE physical web notification instead of 2 (we have 2 beacons). Why is one physical web url keep erasing the other or just fail to show up? On iOS devices, both urls are showing up as notifications.

Both android devices are running the latest android version, my is a Moto X pure edition 2015 and colleague's Nexus 6. Chrome v51.

Again, it's just a VERY frustrating experience on Android.

**Comment by cco3** [comment] 2016-07-07 16:41
Hi @funkybudda, sorry you are having trouble with the Chrome Client.

> On the iOS devices we tested, the notification just WORKS.

There's a significant difference between Android and iOS in that in the iOS widget, you are performing an action that triggers a scan.  On Android, we are scanning passively even when there's no user action, so behavior is not going to be as predictable.

>  it is always ONE physical web notification instead of 2

There should not be two notifications, just one that leads to an activity that displays two URLs, is this the behavior you are seeing.  (Imagine that in a room with 50 beacons, you would not want to see 50 URLs.)

**Comment by scottjenson** [comment] 2016-07-13 22:11
Where are we with this? We are moving from Chrome to Nearby for notifications on Android. Is that working? The advantage of Nearby notifications is that once you open the nearby list, it sticks around (like an app) this gives you a place to return so you're not so dependent on the notification as you were with Chrome.

Closing for now but feel free to reopen if you have more info.

**Closed by scottjenson** 2016-07-13 22:11 UTC

**Comment by schildbach** [comment] 2016-07-26 16:17
The nearby list is still unreliable. Some URLs appear, some not. (All of them are https.) Even less URLs (only one to be exact) appear in the notification bar. I wonder when this Beacon stuff will actually be usable.

**Comment by cco3** [comment] 2016-07-26 16:31
@schildbach, have you tried using the chrome://physical-web tool?  It will tell you if the URLs are being seen and not resolving.  If you have a particular URL that's causing issues, we may be able to help you.

**Comment by ferencbrachmann** [comment] 2016-07-26 16:39
I have a few URLs that we have problems with:
https://beeem.co/em000004
http://goo.gl/wZ3P4z

**Comment by schildbach** [comment] 2016-07-26 16:39
@cco3 I tried all 4 combinations of on/off of Chrome and Play Services physical web support. Example URLs that never appear anywhere: https://heise.de, https://wallet.schildbach.de

**Comment by cco3** [comment] 2016-07-26 17:37
@ferencbrachmann Are you having problems with them now, or just in the past?  They are both working for me.

@schildbach:
https://heise.de redirects to http (it needs to redirect to a final https destination).
https://wallet.schildbach.de has an invalid ssl cert.

I hope that helps!

**Comment by ferencbrachmann** [comment] 2016-07-26 17:50
@cco3 What do you mean by working? Have you encoded them on a beacon and they've shown up on nearby?

**Comment by cco3** [comment] 2016-07-26 18:04
@ferencbrachmann yes, I've encoded them on a beacon.  They appear in chrome and the prototype app.

**Comment by ferencbrachmann** [comment] 2016-07-26 18:34
The issue is not in Chrome but in Nearby.

**Comment by schildbach** [comment] 2016-07-26 18:56
@cco3 Yes it helps, thanks. I didn't know these URLs are checked at all. I'm using it for an application that will intercept the URL before it's being HTTP requested because all the data is already in the app.

**Comment by YogeshDabade** [comment] 2016-08-03 15:48
Hi,
  I am having a beacon transmitting Eddystone URL, I am not getting any problem for iOS phones and tablets but for Android the notification is unreliable, I am able to see the beacon in physical Web app in chrome but its not giving any notification.
I have phone with Android Version 5.0.5 LRX22G.
 I have also tested it on phone with Marshmallow Android version it works fine, I get regular notification from beacon.
Can anybody help where is the problem?

**Comment by scottjenson** [comment] 2016-08-03 17:47
The notification will show up only on screen wake. Be sure to sleep/wake the phone to generate the notification. Things that can cause problems:
* you've swiped away the notifications, that causes us to back off for a while
* you have a Nexus 5x, it has a very bad BLE stack and sometimes misses packets

We understand that notifications aren't a 100% reliable way to find beacons, we're experimenting with more user generated ways to bring up the list.

**Comment by ferencbrachmann** [comment] 2016-08-03 17:49
These wideos explain how it should work:
https://www.youtube.com/channel/UCOWMPr8OqmttcPZkktZldUA

please check your nearby settings in:
Google Settings app -» Nearby Discoveries

**Comment by ferencbrachmann** [comment] 2016-08-03 17:50
Also please check the URL for typical errors/problems. See in my blog post here:
http://blog.beeem.co/2016/03/top-4-things-to-watch-out-for-on-chrome-for-android-with-beacons/

**Comment by YogeshDabade** [comment] 2016-08-04 17:18
@scottjenson @ferencbrachmann Now After switching on  inbuilt  Nearby Services I discovered that It is as reliable  as iOS chrome.

**Comment by mubiesam** [comment] 2016-08-31 02:18
@YogeshDabade +1 Nearby is more reliable...so, what should we focus...Nearby or PW...any suggestion?

**Comment by scottjenson** [comment] 2016-08-31 02:21
There is no switching. It's in Nearby now.

**Comment by frankviljoen** [comment] 2016-12-16 13:28
I have not been able to find Eddystone Beacons in Physical Web on my nexus 6 for some time now, although the beacon is found using other beacon scanner apps?
any ideas?

**Comment by scottjenson** [comment] 2016-12-16 15:31
@frankviljoen I replied to your concerns in the other thread:
* Use verify-physical-web to test the URL you are putting in the beacon
* Use a scanner app (like nRF Connect) to verify you are sending a proper Eddystone packet
If both of those work, your beacon should show up

**Comment by frankviljoen** [comment] 2016-12-16 16:42
@Scott as you say, ' your Beacon should show up ' the operative word being
should???
Tried both those and still no luck. I am finding the Beacon with the newly
downloaded nRF scanner app, but not with physical web or nearby and still
nothing on iOS.
Do you seriously think the everyday consumer is going to go through all
this to bother about a beacon notification??
I'm in the business and I've given up on this ever working.
I programme my own beacon with Eddystone URL and works fine on both Android
and iOS .......

On 16 Dec 2016 15:32, "Scott Jenson" <notifications@github.com> wrote:

@frankviljoen <https://github.com/frankviljoen> I replied to your concerns
in the other thread:

   - Use verify-physical-web to test the URL you are putting in the beacon
   - Use a scanner app (like nRF Connect) to verify you are sending a
   proper Eddystone packet
   If both of those work, your beacon should show up

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/physical-web/issues/720#issuecomment-267619675>,
or mute the thread

**Comment by scottjenson** [comment] 2016-12-16 18:24
I'm sorry you're having so much trouble. Once everything is setup and built
correctly, it should just show up. I'm trying confirm you've actually done
the correct development setup to even *get* to the consumer side of things.

The fact that you are finding the beacon on nRF connect is a great first
step. That helps. Now we need to confirm that the beacon is a secure one (I
hope you agree that security is important). Can you please confirm that
you've typed your shortened beacon URL into verfiy.physical-web.org? If so,
then we move into a different sent of developer questions.

Scott

**Comment by frankviljoen** [comment] 2016-12-16 18:47
Yes Scott, I followed your advice in the first place, and yes I checked the
URL , the only thing I did not need to do was use a url shortner.

the url I am using is https://www.moohbe.com  at verfiy.physical-web.org

after the difficulty I have experienced I really have lost interest,
because I really don't want another beacon scanner app on my phone If i
already have one that works, and I have done all the relevant checks....!

I can get it to work in my own way on both iOS and Android using my own
intelligent beacon

Why should I be having all this difficulty or be questioned as to wether or
not I have the relevant version of Android etc etc.

All my devices are running the latest version. The only reason I made an
approach today was because I am exploring with raspi3.

Thanks Scott.

Regards
Frank Viljoen
WhatsApp & mobile +44 7460020260
www.moohbe.com
SquaredOnline Digital Marketer, Google AdWords Mobile Certified, DSCE
[image: linkedin] <http://uk.linkedin.com/in/frankviljoen>[image: twitter]
<https://twitter.com/NFC_Junkie>  [image: googleplus-2]
<https://plus.google.com/u/0/+FrankViljoen/posts> [image: <a
href="https://www.google.com/intx/en-GB_ALL/work/apps/business/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=TZWWWAE"><img
src="https://www.google.com/work/apps/business/landing/partners/referral/email-assets/GfWAppsButtonEN.png"/></a>]
<https://frankviljoen.ongooglesolutions.com/#whygoogle>

**Comment by adriancretu** [comment] 2016-12-16 19:09
I just used Beacon Toy to create an Eddystone URL with your website. It showed up instantly on another phone after a screen off - screen on (with NO 3rd party apps installed whatsoever). I would suggest that your issues are somewhere else and don't relate to Nearby. Also, it's not exactly clear what you are trying to say by "I can get it to work in my own way on both iOS and Android using my own intelligent beacon" since that would either mean you are using a custom non-Eddystone protocol, or that your beacon is in fact an Eddystone URL (and both things are really off-topic).

**Comment by frankviljoen** [comment] 2016-12-16 19:40
So for the past couple of months we all know there has been a bug within
physical web, yet I am still being questioned about how I approach the
target.
I have an Eddystone beacon setup on raspberry pi3 broadcasting
https://www.moohbe.com which is not being picked up by either PW or iOS.
Yet I have a bluegiga Beacon broadcasting custom Eddystone beacon and
chrome on iOS is detecting the Beacon as is Beacon Scanner, PW on android
is not detecting the Beacon at all..

In my view, the problem lies within PW Android as it has been for the past
number of weeks.




On 16 Dec 2016 19:10, "Adrian Crețu" <notifications@github.com> wrote:

I just used Beacon Toy to create an Eddystone URL with your website. It
showed up instantly on another phone after a screen off - screen on (with
NO 3rd party apps installed whatsoever). I would suggest that your issues
are somewhere else and don't relate to Nearby. Also, it's not exactly clear
what you are trying to say by "I can get it to work in my own way on both
iOS and Android using my own intelligent beacon" since that would either
mean you are using a custom non-Eddystone protocol, or that your beacon is
in fact an Eddystone URL (and both things are really off-topic).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/physical-web/issues/720#issuecomment-267671900>,
or mute the thread

**Comment by adriancretu** [comment] 2016-12-16 19:50
I'm not questioning your approach, I'm just saying that your issue cannot be reproduced in clean conditions. As long as your BLE beacon is picked up by the device (checked), it contains a correct Eddystone-URL payload format (checked), is handled by the official Google Physical Web proxy (checked), and it then displays back on the device after a screen-on (again, checked) then your issue lies either **before** or **after** this chain. Examples:
- bad beacon
- bad broadcast payload
- Nearby not opted-in or disabled by user

**Comment by adriancretu** [comment] 2016-12-16 19:58
And BTW, there is no such thing as "custom Eddystone beacon". Eddystone is a well-formed specification, not a beacon :) My guess is that your hardware stack (Raspberry Pi) does not do things correctly on the bottom layer, which causes it not to be detected by Chrome on iOS / Android's Play Services.

**Comment by frankviljoen** [comment] 2016-12-16 20:17
Do you know what, I am tired of being insulted and to confirm, I have
followed protocol, followed checks and followed tests and I have a beacon
that works, except on Physical Web. I have checked my raspberry pi3 coding
at http://yencarnacion.github.io/eddystone-url-calculator/ and still no
luck.
Until PW gets theie act in order, I don't see any more options of
troubleshooting or based on the feedback in the forum, even care to
troubleshoot anymore!
Frank


Regards
Frank Viljoen
WhatsApp & mobile +44 7460020260
www.moohbe.com
SquaredOnline Digital Marketer, Google AdWords Mobile Certified, DSCE
[image: linkedin] <http://uk.linkedin.com/in/frankviljoen>[image: twitter]
<https://twitter.com/NFC_Junkie>  [image: googleplus-2]
<https://plus.google.com/u/0/+FrankViljoen/posts> [image: <a
href="https://www.google.com/intx/en-GB_ALL/work/apps/business/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=TZWWWAE"><img
src="https://www.google.com/work/apps/business/landing/partners/referral/email-assets/GfWAppsButtonEN.png"/></a>]
<https://frankviljoen.ongooglesolutions.com/#whygoogle>

**Comment by adriancretu** [comment] 2016-12-16 20:36
I don't see how you'd think such an attitude would be constructive. Your URL is validated just fine, and when broadcasted by a beacon, it shows up as an Android notification via Nearby (assuming you're actually using latest Play Services like you said, and you did not opt-out explicitly to Nearby links/messages in the settings). If you want help beyond this point, you will need to provide more details, as troublesome as that may sound for you.

**Comment by frankviljoen** [comment] 2016-12-16 20:47
Once again you choose to insult me - (assuming you're actually using latest
Play Services like you said,) having done all the necessary tests.

At the end of the day, I have a product that works on both Android and iOS,
with or without physical web.

Frank





On 16 Dec 2016 20:37, "Adrian Crețu" <notifications@github.com> wrote:

I don't see how you'd think such an attitude would be constructive. Your
URL is validated just fine, and when broadcasted by a beacon, it shows up
as an Android notification via Nearby (assuming you're actually using
latest Play Services like you said, and you did not opt-out explicitly to
Nearby links/messages in the settings). If you want help beyond this point,
you will need to provide more details, as troublesome as that may sound for
you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/physical-web/issues/720#issuecomment-267690174>,
or mute the thread

**Comment by adriancretu** [comment] 2016-12-16 21:04
![screenshot_20161216-225731](https://cloud.githubusercontent.com/assets/9372489/21278442/e06debe0-c3e3-11e6-9a26-0c56d38f64f5.png)
![screenshot_20161216-225623](https://cloud.githubusercontent.com/assets/9372489/21278444/e06fbfb0-c3e3-11e6-8fbc-97be7c6a74c8.png)
![screenshot_20161216-225558](https://cloud.githubusercontent.com/assets/9372489/21278443/e06f589a-c3e3-11e6-9f46-3864be6e52e2.png)

**Comment by frankviljoen** [comment] 2016-12-16 21:15
Seriously, so what? I can send you numerous screenshot showing failures, I
am just not bothered!
Clearly your system works, mine and multiple other users does not work!
End of conversation

**Comment by WingGithub** [comment] 2017-03-18 06:52
I don't know if people realize this but there is a proxy betweenwhat the beacon broadcasts and where it shows up on the Physical Web app or Nearby. This proxy filters out everything that is not HTTPS and URLs it thinks is not valid. If you use a test URL like https://example.org, it will get filtered out. Other URLS may also be dropped based on whatever rules google has decided on. There is the catch.
